### PR TITLE
tools: add gdb pretty-print

### PR DESCRIPTION
**Pull request by christophefontaine**
Ease our lives with some pretty print in gdb.
"p iface" now prints the content of "info" according to the port type.

Mac address, IPv4 and IPv6 are printed in a human readable form as well.
```
(gdb) p *ifaces[257]
$177 = {base = {id = 257, type = GR_IFACE_TYPE_PORT, mode = GR_IFACE_MODE_L3, flags = GR_IFACE_F_UP, state = GR_IFACE_S_RUNNING, mtu = 1500, {vrf_id = 0, domain_id = 0}}, subinterfaces = 0x0, name = 0x1489950 "cv0", info = {n_rxq = 1, n_txq = 1, rxq_size = 4096,
    txq_size = 4096, link_speed = 25000, mac = b4:83:51:05:43:ca}}

(gdb) p *base
$178 = {type = GR_NH_T_L3, af = GR_AF_IP6, state = GR_NH_S_NEW, flags = 0, nh_id = 0, vrf_id = 0, iface_id = 257, mac = 00:00:00:00:00:00, prefixlen = 0 '\000', origin = GR_NH_ORIGIN_USER, {addr = {<No data fields>}, ipv4 = 32.1.0.1, ipv6 = 2001:1::42}}
```

## Summary by CodeRabbit

- **New Features**
  - Added GDB pretty-printers for IPv4, IPv6, Ethernet addresses, and interface structures for clearer, human-readable debugging output.
  - Automatic loading/registration so printers are available during debug sessions.

- **Documentation**
  - New "Debugging tools" section with setup, auto-load guidance, and verification steps for the printers.

- **Chores**
  - Updated GDB configuration to ignore signal 35 and auto-load the pretty-printer module.

### CODE REVIEW

File: devtools/gdb_pprint.py [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+import gdb
+import gdb.printing
+
+
+class IP4Address:
+    def __init__(self, val):
+        self.val = val
+
+    def to_string(self):
+        return str(ipaddress.IPv4Address(self.val.bytes))
```
Comment (christophefontaine) [inline devtools/gdb_pprint.py:15]: This doesn't work on RHEL 9.4:
```'gdb.Value' object has no attribute 'bytes'```
